# Generated by Django 3.1.6 on 2021-03-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats_admins',
            options={'ordering': ['-date_creating'], 'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['date_creating'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
