# Generated by Django 3.1.6 on 2021-03-10 08:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email')),
                ('image', models.ImageField(default='../static/Users/images/default-user-image.jpeg', upload_to='../static/Users/images', verbose_name='image')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='last_name')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='first_name')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000, verbose_name='text')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'UserPost',
                'verbose_name_plural': 'UserPosts',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.CreateModel(
            name='UserPostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userposts', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'UserPostLike',
                'verbose_name_plural': 'UserPostLikes',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.CreateModel(
            name='UserPostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=5000, verbose_name='comment')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userposts', verbose_name='post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'UserPostComment',
                'verbose_name_plural': 'UserPostComments',
                'ordering': ['date_creating'],
            },
        ),
        migrations.CreateModel(
            name='User_followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('user_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower', to=settings.AUTH_USER_MODEL, verbose_name='user_follower')),
            ],
            options={
                'verbose_name': 'Users_follower',
                'verbose_name_plural': 'Users_followers',
                'ordering': ['date_creating'],
                'unique_together': {('user', 'user_follower')},
            },
        ),
    ]
