# Generated by Django 3.1.6 on 2021-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=2000, verbose_name='description')),
                ('image', models.ImageField(default='../static/Communities/images/default-community-image.jpeg', upload_to='../static/Communities/images', verbose_name='image')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.CreateModel(
            name='Community_admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
            ],
            options={
                'verbose_name': 'Community_admin',
                'verbose_name_plural': 'Community_admins',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.CreateModel(
            name='Community_followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
            ],
            options={
                'verbose_name': 'Community_follower',
                'verbose_name_plural': 'Community_followers',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'CommunityCategory',
                'verbose_name_plural': 'Categories',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=5000, verbose_name='comment')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
            ],
            options={
                'verbose_name': 'CommunityPostComment',
                'verbose_name_plural': 'CommunityPostComments',
                'ordering': ['date_creating'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
            ],
            options={
                'verbose_name': 'CommunityPostsLike',
                'verbose_name_plural': 'CommunityPostsLikes',
                'ordering': ['-date_creating'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000, verbose_name='text')),
                ('date_creating', models.DateTimeField(auto_now_add=True, verbose_name='date_creating')),
            ],
            options={
                'verbose_name': 'CommunityPost',
                'verbose_name_plural': 'CommunityPosts',
                'ordering': ['-date_creating'],
            },
        ),
    ]
