# Generated by Django 3.1.6 on 2021-03-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communities', '0003_auto_20210310_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community_admins',
            options={'ordering': ['-date_creating'], 'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='community_followers',
            options={'ordering': ['-date_creating'], 'verbose_name': 'Follower', 'verbose_name_plural': 'Followers'},
        ),
        migrations.AlterModelOptions(
            name='communitycategory',
            options={'ordering': ['-date_creating'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='communitypostcomments',
            options={'ordering': ['date_creating'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='communitypostlikes',
            options={'ordering': ['-date_creating'], 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='communityposts',
            options={'ordering': ['-date_creating'], 'verbose_name': 'post', 'verbose_name_plural': 'Posts'},
        ),
    ]
